import type { ContextPack } from "@loopforge/core"

export const BUILT_IN_PACKS: ContextPack[] = [
  {
    id: "pack-auth",
    projectId: "",
    name: "Authentication & Authorization",
    description: "Auth middleware, session handling, JWT config, and security-related files.",
    filePatterns: ["**/auth/**", "**/middleware/**", "**/*auth*", "**/*session*", "**/*jwt*"],
    ticketLabels: ["security"],
    workflowIds: [],
    isBuiltIn: true,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "pack-database",
    projectId: "",
    name: "Database & Migrations",
    description: "Database schemas, migrations, models, and repository/store patterns.",
    filePatterns: ["**/migrations/**", "**/schema*", "**/models/**", "**/*repository*", "**/*store*"],
    ticketLabels: ["debt"],
    workflowIds: [],
    isBuiltIn: true,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "pack-api",
    projectId: "",
    name: "API Layer",
    description: "Routes, controllers, handlers, and API surface files.",
    filePatterns: ["**/routes/**", "**/controllers/**", "**/handlers/**", "**/api/**"],
    ticketLabels: ["feature", "bug"],
    workflowIds: [],
    isBuiltIn: true,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "pack-ui",
    projectId: "",
    name: "Frontend & Components",
    description: "UI components, pages, app directories, and stylesheets.",
    filePatterns: ["**/components/**", "**/pages/**", "**/app/**", "**/*.tsx", "**/*.css"],
    ticketLabels: ["feature"],
    workflowIds: [],
    isBuiltIn: true,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "pack-config",
    projectId: "",
    name: "Configuration & Infrastructure",
    description: "Config files, Docker, environment files, CI pipelines, and YAML configs.",
    filePatterns: ["**/*.config.*", "**/docker*", "**/.env*", "**/ci/**", "**/*.yaml", "**/*.yml"],
    ticketLabels: ["debt"],
    workflowIds: [],
    isBuiltIn: true,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "pack-testing",
    projectId: "",
    name: "Tests & Quality",
    description: "Unit tests, integration tests, specs, and end-to-end test files.",
    filePatterns: ["**/*.test.*", "**/*.spec.*", "**/tests/**", "**/e2e/**"],
    ticketLabels: ["bug", "debt"],
    workflowIds: [],
    isBuiltIn: true,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
]
